create table "public"."hackathons" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" text,
    "description" text
);


alter table "public"."hackathons" enable row level security;

CREATE UNIQUE INDEX hackathons_pkey ON public.hackathons USING btree (id);

alter table "public"."hackathons" add constraint "hackathons_pkey" PRIMARY KEY using index "hackathons_pkey";
alter table "public"."hackathons" add column "updated_at" timestamp with time zone default now();